version: "3.9"

services:
  db:
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app
      - POSTGRESQL_DATABASE=blogging-db
    ports:
      - "5455:5432"
    cpu_shares: 512
    mem_limit: 512M

  api:
    image: node:20-alpine
    depends_on:
      - db
    container_name: blogging-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    ports:
      - 3001:3001
    working_dir: /usr/app
    restart: unless-stopped
    command: npm start
    environment: 
      - DB_PORT=5432
      - DB_HOST=db

volumes:
  node_modules:
