name: Build and Push Docker Image

on:
  push:
    branches: 
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


      - name: Build Docker Image
        run: 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blogging-api:latest --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} .

      - name: Push Docker Image
        run: 
          docker push ${{ secrets.DOCKER_USERNAME }}/blogging-api:latest